# Generated by Django 4.2.5 on 2023-12-23 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompliancePolicy',
            fields=[
                ('policyID', models.AutoField(primary_key=True, serialize=False)),
                ('policyName', models.CharField(max_length=255)),
                ('policyDescription', models.TextField()),
                ('acknowledgementDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employeeID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phoneNumber', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=255)),
                ('dateOB', models.DateTimeField()),
                ('jobTitle', models.CharField(max_length=255)),
                ('dateOfHire', models.DateTimeField()),
                ('salary', models.IntegerField(default=0)),
                ('bankaccNo', models.IntegerField(default=0)),
                ('taxExemption', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('reviewID', models.AutoField(primary_key=True, serialize=False)),
                ('reviewDate', models.DateTimeField()),
                ('reviewer', models.CharField(max_length=255)),
                ('performanceScore', models.IntegerField(default=0)),
                ('comment', models.TextField()),
                ('employeeID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HRapp.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('payrollID', models.AutoField(primary_key=True, serialize=False)),
                ('payrollStartDate', models.DateTimeField()),
                ('payrollEndDate', models.DateTimeField()),
                ('regularHours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('overtimeHours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('employeeID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HRapp.employees')),
            ],
        ),
        migrations.CreateModel(
            name='OnBoarding',
            fields=[
                ('onboardingID', models.AutoField(primary_key=True, serialize=False)),
                ('jobDescription', models.TextField()),
                ('salaryRange', models.IntegerField(default=0)),
                ('employeeID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_onboarding_set', to='HRapp.employees')),
                ('jobTitleReference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobtitle_onboarding_set', to='HRapp.employees')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('requestID', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('reason', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('employeeID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HRapp.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('benefitID', models.AutoField(primary_key=True, serialize=False)),
                ('benefitName', models.CharField(max_length=255)),
                ('typeOfBenefit', models.CharField(max_length=100)),
                ('benefitDescription', models.TextField()),
                ('benefitStartDate', models.DateTimeField()),
                ('benefitEndDate', models.DateTimeField()),
                ('employeeID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HRapp.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendanceID', models.AutoField(primary_key=True, serialize=False)),
                ('clockIn', models.DateTimeField()),
                ('clockOut', models.DateTimeField()),
                ('employeeID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HRapp.employees')),
            ],
        ),
    ]
