# Generated by Django 3.0.7 on 2024-02-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hrmanagement_app', '0003_auto_20240105_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffpoint',
            old_name='position_insentive_point',
            new_name='position_incentive_point',
        ),
    ]
