# Generated by Django 3.0.7 on 2024-03-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hrmanagement_app', '0004_auto_20240223_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='pdf_file',
            field=models.FileField(default=None, upload_to='media/'),
        ),
    ]
