# Generated by Django 3.0.7 on 2024-03-30 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hrmanagement_app', '0005_staff_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pdf_file', models.FileField(default=None, upload_to='media/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hrmanagement_app.Staff')),
            ],
        ),
    ]
