# Generated by Django 3.0.7 on 2024-03-30 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hrmanagement_app', '0006_contracts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='pdf_file',
        ),
    ]
