# Generated by Django 3.0.7 on 2024-04-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hrmanagement_app', '0007_remove_staff_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('policy_name', models.CharField(max_length=200)),
                ('policy_document', models.FileField(default=None, upload_to='media/')),
            ],
        ),
    ]
