# Generated by Django 3.0.7 on 2024-04-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hrmanagement_app', '0008_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereportmanager',
            name='return_date',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='leavereportstaff',
            name='return_date',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
